os:
  - linux

language: python

python:
  - 2.7
  - pypy
  - 3.5
  - 3.6
  - nightly
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - nosetests
  - pip install flake8
  - flake8 .

after_success:
  - coveralls
